import { featureName } from './display';
import { useMemo, useState } from 'react';
import { applyEdit, previewEdit, finalizeCharacter, recoverResources, recoverSelectedResources, settleAbility, useAbility, castSpell, type Engine, type Character, type Edit, type EditPreview, type SpellTurn } from '../../src/index';
import { labelFromId } from './workspace';
import { SelectionCard } from './SelectionCard';
import { Modal } from './Modal';
import { FeatureRules, RulesText } from './RulesText';

export function CharacterBuilder({engine,character,update,openFeature,report}:{engine:Engine;character:Character;update:(c:Character)=>void;openFeature:(id:string)=>void;report:(message:string)=>void}) {
  const result=useMemo(()=>engine.evaluate(character),[engine,character]);
  const [tab,setTab]=useState('choices'),[level,setLevel]=useState('all'),[classId,setClassId]=useState(engine.catalogue.classes[0]?.id??'');
  const [preview,setPreview]=useState<{edits:Edit[];result:EditPreview}|null>(null);
  const initialBudget=Object.fromEntries([...new Set(result.capabilities.flatMap(c=>c.definition.action?[c.definition.action.kind]:[]))].map(kind=>[kind,1]));
  const [budget,setBudget]=useState<Record<string,number>>(initialBudget),[actions,setActions]=useState<Record<string,number>>(initialBudget);
  const [turn,setTurn]=useState<SpellTurn>({bonusActionSpell:false,otherSpell:false,onlyActionCantrips:true});
  const attempt=(action:()=>void)=>{try{action();}catch(e){report(e instanceof Error?e.message:String(e));}};
  const edit=(edits:Edit[])=>attempt(()=>{
    if(character.buildState==='draft') update(applyEdit(engine,character,edits,crypto.randomUUID()));
    else setPreview({edits,result:previewEdit(engine,character,edits)});
  });
  const slots=result.selections.filter(s=>level==='all' || (s.id.startsWith('advancement/')?'origins':s.id.match(/^class\/[^/]+\/(\d+)/)?.[1]??'extra')===level);
  const levels=[...new Set(result.selections.map(s=>s.id.startsWith('advancement/')?'origins':s.id.match(/^class\/[^/]+\/(\d+)/)?.[1]??'extra'))].sort((a,b)=>Number(a)-Number(b));
  const inputs=engine.catalogue.system.stats.filter(s=>s.kind==='input');
  const incomplete=result.diagnostics.filter(d=>d.severity==='incomplete').length;
  const ready=character.buildState!=='draft' && result.status==='valid';
  return <>
    <div className="character-title"><div><p className="eyebrow">Character workspace</p><input className="name-input" aria-label="Character name" key={character.id} defaultValue={character.name} onBlur={e=>{const name=e.target.value.trim()||'Unnamed character';e.target.value=name;if(name!==character.name) update({...character,name});}} /><p className="muted">{engine.catalogue.system.name} · level {result.characterLevel}</p></div><span role="status" aria-live="polite" className={`badge ${result.status}`}>{result.status==='valid'&&character.buildState==='draft'?'Ready to finalize':result.status}</span></div>
    <div className="summary-strip"><div><span>Selections</span><strong>{result.selections.reduce((n,s)=>n+s.picks.length,0)}</strong></div><div><span>Open requirements</span><strong>{result.diagnostics.length}</strong></div><div><span>Acquired Features</span><strong>{result.instances.filter(i=>i.active&&i.eligible).length}</strong></div><div><span>Resource pools</span><strong>{Object.keys(result.resources).length}</strong></div></div>
    <nav className="subnav" aria-label="Character sections">{[['choices','Build & choices'],['stats','Character sheet'],['resources','Abilities & resources']].map(([id,name])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{name}</button>)}</nav>
    {result.diagnostics.length>0 && <details className="diagnostics" open={result.status==='invalid'}><summary>{result.status==='invalid'?'Build needs repair':`${incomplete} requirements to finish`}</summary><ul>{result.diagnostics.map((d,i)=><li key={i}><strong>{d.message}</strong><small>{d.path}</small></li>)}</ul><p>Totals are provisional until every requirement is satisfied.</p></details>}
    {tab==='choices' && <div className="builder-grid"><aside className="builder-setup">
      <section className="panel"><h3>Class progression</h3>{character.progressions.map(p=>{const cls=engine.catalogue.classes.find(c=>c.id===p.class);return cls?.description?<details key={`rules:${p.id}`}><summary>Read {cls.name} Class rules</summary><RulesText text={cls.description} source={cls.source} /></details>:null;})}{character.progressions.map(p=><label key={p.id}>{engine.catalogue.classes.find(c=>c.id===p.class)?.name??p.class}<input type="number" key={`${p.id}:${p.level}`} min="0" max={engine.catalogue.classes.find(c=>c.id===p.class)?.maximumLevel} defaultValue={p.level} onBlur={e=>{if(e.target.value==='')e.target.value=String(p.level);if(Number(e.target.value)!==p.level)edit([{kind:'level',progression:p.id,level:Number(e.target.value)}]);}} />{character.buildState==='draft'&&<button className="link" onClick={()=>edit([{kind:'removeProgression',progression:p.id}])}>Remove progression</button>}</label>)}
      {engine.catalogue.classes.length>0&&<><label>Add a class<select value={classId} onChange={e=>setClassId(e.target.value)}>{engine.catalogue.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="quiet full" disabled={(!engine.catalogue.system.allowMultipleClasses&&character.progressions.length>0)||(engine.catalogue.system.allowDuplicateClasses===false&&character.progressions.some(p=>p.class===classId))} onClick={()=>edit([{kind:'addProgression',progression:{id:crypto.randomUUID(),class:classId,level:1}}])}>Add progression</button></>}
      {!engine.catalogue.system.allowMultipleClasses&&<p className="muted small">This configuration permits one class progression.</p>}
      <details><summary>Advancement history</summary><ol>{character.history.map((h,i)=><li key={i}>{engine.catalogue.classes.find(c=>c.id===character.progressions.find(p=>p.id===h.progression)?.class)?.name} {h.level}</li>)}</ol></details></section>
      <section className="panel"><h3>Basic stats</h3>{inputs.map(s=><label key={s.id}>{s.name}<input key={`${character.id}:${s.id}:${character.inputs[s.id]}`} type="number" defaultValue={character.inputs[s.id]??''} min={s.minimum} max={s.maximum} step={s.integer?1:'any'} onBlur={e=>{if(e.target.value==='')e.target.value=String(character.inputs[s.id]??'');if(e.target.value!=='' && Number(e.target.value)!==character.inputs[s.id])edit([{kind:'input',stat:s.id,value:Number(e.target.value)}]);}} /></label>)}</section>
    </aside><section><div className="row"><h2>Feature selections</h2><label className="compact">Show<select aria-label="Filter selections by level" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">All levels</option>{levels.map(l=><option value={l} key={l}>{l==='origins'?'Origins':l==='extra'?'Additional Features':`Class level ${l}`}</option>)}</select></label></div>
      <p className="muted">Each slot is independent. Choose a Feature to reveal its parameters and nested choices.</p>
      {slots.map(slot=>{
        const owner=result.instances.find(i=>i.id===slot.owner),name=owner?featureName(engine.catalogue.features.find(f=>f.id===owner.feature)):undefined;
        return <SelectionCard key={slot.id} slot={slot} engine={engine} character={character} edit={edit} openFeature={openFeature} ownerName={name} />;
      })}
      {!slots.length&&<p>No selections at this level.</p>}
      <details className="panel"><summary>Additional root Features</summary><p className="muted">Add supported extra acquisitions from this System. Engine prerequisites and resource rules still apply.</p><RootPicker engine={engine} character={character} edit={edit} level={result.characterLevel} />{character.roots.map(root=><div className="row" key={root.id}><button className="link" onClick={()=>openFeature(root.feature)}>{featureName(engine.catalogue.features.find(f=>f.id===root.feature))}</button><button className="quiet" onClick={()=>edit([{kind:'removeRoot',id:root.id}])}>Remove</button></div>)}</details>
      {character.buildState==='draft'&&<div className="finalize"><p>{result.status==='valid'?'All requirements are met. Finalize to use abilities and resources.':'Drafts are saved as you work. Finish the requirements to finalize.'}</p><button disabled={result.status!=='valid'} onClick={()=>attempt(()=>update(finalizeCharacter(engine,character,crypto.randomUUID())))}>Finalize character</button></div>}
    </section></div>}
    {tab==='stats'&&<><h2>Calculated stats</h2><p className="muted">Open a stat to inspect its base and Feature modifiers. {result.provisional?'These totals are provisional.':''}</p><div className="stat-grid">{engine.catalogue.system.stats.map(s=><details className="stat-tile" key={s.id}><summary><span>{s.name}</span><strong>{result.stats[s.id]?.value??'—'}</strong></summary><p>Base: {result.stats[s.id]?.base??'—'}</p>{result.stats[s.id]?.modifiers.map((m,i)=><p key={i}>{featureName(engine.catalogue.features.find(f=>f.id===result.instances.find(i=>i.id===m.source)?.feature))} · {m.operation} {m.amount} · {m.applied?'Applied':m.reason}</p>)}{s.kind==='derived'&&<pre>{JSON.stringify(s.expression,null,2)}</pre>}</details>)}</div><h2>Acquired Features</h2><div className="feature-list">{result.instances.filter(i=>i.active).map(i=>{const feature=engine.catalogue.features.find(f=>f.id===i.feature)!;return <details className="acquired-feature" key={i.id}><summary>{featureName(feature)}<span className={`badge ${i.eligible?'valid':'invalid'}`}>{i.eligible?'Active':'Unmet requirements'}</span></summary><FeatureRules feature={feature} engine={engine} openFeature={openFeature} /><button className="link" onClick={()=>openFeature(i.feature)}>View Feature →</button></details>;})}</div></>}
    {tab==='resources'&&<><h2>Resources</h2><p className="muted">Finalize a valid character to use these controls. Resource expenditure is preserved when the build changes.</p><div className="stat-grid">{Object.values(result.resources).map(p=><article className="stat-tile" key={p.id}><span>{labelFromId(p.key)}</span><strong>{p.available} / {p.capacity}</strong><p className="muted small">{p.spent} spent · {p.reserved} reserved · {p.units}</p><p className="muted small">{p.recovery.map(r=>labelFromId(r.event)).join(' · ')||'No automatic recovery'}</p></article>)}</div>
      <div className="toolbar">{[...new Set(Object.values(result.resources).flatMap(p=>p.recovery.map(r=>r.event)))].map(event=><button className="quiet" key={event} disabled={!ready} onClick={()=>attempt(()=>update(recoverResources(engine,character,event,crypto.randomUUID())))}>{labelFromId(event)}</button>)}</div>
      {engine.catalogue.system.commandRules?.selectedRecovery&&<SelectedRecovery engine={engine} character={character} ready={ready} update={update} report={report} />}
      {Object.entries(character.pending).map(([id,pending])=><section className="panel" key={id}><h3>Resolve reserved ability use</h3><p className="muted small">{id}</p><div className="toolbar">{pending.spendOnOutcomes.map(outcome=><button className="quiet" key={outcome} disabled={!ready} onClick={()=>attempt(()=>update(settleAbility(character,id,outcome,crypto.randomUUID())))}>{labelFromId(outcome)} · consume</button>)}<button className="quiet" disabled={!ready} onClick={()=>attempt(()=>{const release=`release:${crypto.randomUUID()}`;update(settleAbility(character,id,release,crypto.randomUUID()));})}>Release reservation</button></div></section>)}
      <h2>Abilities</h2><div className="panel"><div className="row"><h3>Turn budget</h3><button className="quiet" onClick={()=>{setActions({...budget});setTurn({bonusActionSpell:false,otherSpell:false,onlyActionCantrips:true});}}>Start new turn</button></div><div className="input-grid">{[...new Set([...Object.keys(actions),...result.capabilities.flatMap(c=>c.definition.action?[c.definition.action.kind]:[])])].map(kind=><label key={kind}>{labelFromId(kind)}<input type="number" min="0" value={actions[kind]??0} onChange={e=>{const amount=Math.max(0,Number(e.target.value));setActions({...actions,[kind]:amount});setBudget({...budget,[kind]:amount});}} /></label>)}</div><p className="muted small">Turn and action budgets are session controls. Set them to what is available at your table.</p></div>
      {result.capabilities.map(c=><article className="component" key={c.id}><div className="row"><div><h3>{c.definition.name}</h3><p className="muted small">{c.definition.action?`${c.definition.action.amount} ${labelFromId(c.definition.action.kind)}`:'No action cost'} · {Object.entries(c.costs).map(([id,n])=>`${n} ${result.resources[id]?.key}`).join(', ')||'No resource cost'}</p></div><button className="quiet" disabled={!ready || c.definition.name===engine.catalogue.system.commandRules?.selectedRecovery?.capabilityName} onClick={()=>attempt(()=>{
        const policy=engine.catalogue.system.commandRules?.spellTurn;
        if(policy&&typeof c.definition.metadata?.[policy.castingAbilityKey]==='string') { const used=castSpell(engine,character,c.id,crypto.randomUUID(),turn,{actions});update(used.character);setActions(used.actions??actions);setTurn(used.turn); }
        else {const used=useAbility(engine,character,c.id,crypto.randomUUID(),{actions});update(used.character);setActions(used.actions??actions);}
      })}>Use ability</button></div>{c.definition.description&&<p>{c.definition.description}</p>}<button className="link" onClick={()=>openFeature(result.instances.find(i=>i.id===c.source)!.feature)}>View source Feature →</button></article>)}
      <p className="muted">Ability effects, targets, dice, and triggers require adjudication. Long casting times and reactions on other turns require the appropriate turn budget.</p>
    </>}
    {preview&&<Modal title="Review build change" onClose={()=>setPreview(null)}><p>{preview.result.added.length} Features added · {preview.result.removed.length} removed</p><p>Stats affected: {preview.result.changedStats.map(labelFromId).join(', ')||'None'}</p><p>Resource pools affected: {preview.result.changedResources.length}</p><p>Result: {preview.result.after.status}. Dependent choices may need repair.</p><div className="toolbar"><button onClick={()=>attempt(()=>{update(applyEdit(engine,character,preview.edits,crypto.randomUUID()));setPreview(null);})}>Apply change</button><button className="quiet" onClick={()=>setPreview(null)}>Cancel</button></div></Modal>}
  </>;
}
function SelectedRecovery({engine,character,ready,update,report}:{engine:Engine;character:Character;ready:boolean;update:(c:Character)=>void;report:(message:string)=>void}) {
  const policy=engine.catalogue.system.commandRules!.selectedRecovery!;
  const [counts,setCounts]=useState<Record<string,number>>({}),[rest,setRest]=useState('');
  const result=engine.evaluate(character);
  const events=character.events.filter(e=>{try{const data=JSON.parse(e.fingerprint);return data.kind==='recover'&&data.recoveryEvent===policy.requiredEvent;}catch{return false;}});
  return <section className="panel"><h3>{policy.capabilityName}</h3><p className="muted small">Recovery budget: {result.stats[policy.budgetStat].value}. Targets use the weights declared by this System.</p><label>Completed {labelFromId(policy.requiredEvent)}<select value={rest} onChange={e=>setRest(e.target.value)}><option value="">Choose a recorded event…</option>{events.map((e,i)=><option key={e.id} value={e.id}>Event {i+1} · {e.id.slice(0,8)}</option>)}</select></label><div className="input-grid">{Object.entries(policy.targets).map(([id,target])=>{
    const pool=Object.values(result.resources).find(p=>p.key===target.key&&p.scope===target.scope);
    return <label key={id}>{labelFromId(target.key)} · weight {target.weight}<input type="number" min="0" max={pool?.spent??0} step="1" value={counts[id]??0} onChange={e=>setCounts({...counts,[id]:Number(e.target.value)})} /></label>;
  })}</div><button className="quiet" disabled={!ready||!rest} onClick={()=>{try{update(recoverSelectedResources(engine,character,Object.fromEntries(Object.entries(counts).filter(([,n])=>n!==0)),rest,crypto.randomUUID()));setCounts({});}catch(e){report(e instanceof Error?e.message:String(e));}}}>Recover allocation</button></section>;
}
function RootPicker({engine,character,edit,level}:{engine:Engine;character:Character;edit:(e:Edit[])=>void;level:number}) {
  const [query,setQuery]=useState(''),[selected,setSelected]=useState('');
  const policy=engine.catalogue.system.rootCandidates;
  const choices=engine.catalogue.features.filter(f=>(!policy?.ids||policy.ids.includes(f.id))&&(!policy?.tags||policy.tags.every(t=>f.tags?.includes(t)))&&featureName(f).toLowerCase().includes(query.toLowerCase())).slice(0,50);
  return <><label>Find additional Feature<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}} /></label><label>Feature<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose…</option>{choices.map(f=><option value={f.id} key={f.id}>{featureName(f)}</option>)}</select></label><button className="quiet" disabled={!selected} onClick={()=>edit([{kind:'root',acquisition:{id:crypto.randomUUID(),feature:selected,acquiredCharacterLevel:level,...(character.history.length?{acquiredEvent:character.history.length-1}:{})}}])}>Add Feature</button></>;
}
