import { Engine, clone } from '@/src/engine.js';
import type { Catalogue } from '@/src/model.js';
import { SystemRegistry, getFeatureCoverage } from '@/src/system-loader.js';
import metadata from '@/src/systems/dnd5e-2014/metadata.json' with { type: 'json' };
import systemFile from '@/src/systems/dnd5e-2014/system.json' with { type: 'json' };
import type { Dnd2014Options } from '@/src/systems/dnd5e-2014/types/Dnd2014Options.js';
import type { Spell } from '@/src/systems/dnd5e-2014/types/Spell.js';
export { castSpell, castWizardSpell, recoverArcaneSlots, type SpellTurn } from '@/src/policy-commands.js';
export type { Dnd2014Options } from '@/src/systems/dnd5e-2014/types/Dnd2014Options.js';
export type { Spell } from '@/src/systems/dnd5e-2014/types/Spell.js';
export type { SupportedClass } from '@/src/systems/dnd5e-2014/types/SupportedClass.js';
export const armor = metadata.armor;
export const wizardSpells: Spell[] = metadata.wizardSpells;
export const classInfo = metadata.classInfo;
export const dnd2014Coverage = metadata.coverage;
const registry = new SystemRegistry();
registry.load(systemFile);
export const createDnd2014Engine = (options: Dnd2014Options = {}): Engine => registry.createEngine(systemFile.id, systemFile.revision, Object.fromEntries(Object.entries(options).filter(([, value]) => value !== undefined)));
export const createDnd2014Catalogue = (options: Dnd2014Options = {}): Catalogue => clone(createDnd2014Engine(options).catalogue);
export const getDnd2014FeatureCoverage = (catalogue: Catalogue = createDnd2014Catalogue()) => getFeatureCoverage(catalogue);
